import * as turf from "@turf/turf";
import tokml from "tokml";

export function exportGeoJson(points) {
  return turf.featureCollection(
    points.map((point) =>
      turf.point(point.coordinates, {
        id: point.id,
        label: point.label,
        type: point.type,
        latitude: point.lat,
        longitude: point.lng,
        utm_zone: point.utm?.zone,
        utm_hemisphere: point.utm?.hemisphere,
        utm_easting: point.utm?.easting,
        utm_northing: point.utm?.northing
      })
    )
  );
}

export function exportCsv(points) {
  const header = [
    "id",
    "label",
    "type",
    "latitude",
    "longitude",
    "utm_zone",
    "utm_hemisphere",
    "utm_easting",
    "utm_northing"
  ];

  const rows = points.map((point) => [
    point.id,
    point.label,
    point.type,
    point.lat,
    point.lng,
    point.utm?.zone ?? "",
    point.utm?.hemisphere ?? "",
    point.utm?.easting ?? "",
    point.utm?.northing ?? ""
  ]);

  return [header, ...rows]
    .map((row) => row.map((value) => escapeCsv(value)).join(","))
    .join("\n");
}

export function exportKml(points) {
  const geojson = exportGeoJson(points);
  return tokml(geojson, {
    name: "label",
    description: "type"
  });
}

export function exportGpx(points) {
  const waypoints = points
    .map((point) => {
      const lat = Number(point.lat);
      const lon = Number(point.lng);

      if (!Number.isFinite(lat) || !Number.isFinite(lon)) {
        return "";
      }

      const description = [
        point.type,
        point.utm?.zone ? `UTM ${point.utm.zone}${point.utm.hemisphere || ""}` : "",
        point.utm?.easting ? `E ${point.utm.easting}` : "",
        point.utm?.northing ? `N ${point.utm.northing}` : ""
      ]
        .filter(Boolean)
        .join(" | ");

      return [
        `<wpt lat="${lat.toFixed(8)}" lon="${lon.toFixed(8)}">`,
        `  <name>${escapeXml(point.label || point.id || "Waypoint")}</name>`,
        `  <cmt>${escapeXml(point.type || "POINT")}</cmt>`,
        `  <desc>${escapeXml(description || "Point exported from GCP Planner App")}</desc>`,
        `  <type>${escapeXml(point.type || "POINT")}</type>`,
        "  <sym>Waypoint</sym>",
        "</wpt>"
      ].join("\n");
    })
    .filter(Boolean)
    .join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<gpx version="1.1" creator="GCP Planner App" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">',
    "  <metadata>",
    "    <name>GCP Planner Export</name>",
    "    <desc>Waypoint export generated by GCP Planner App</desc>",
    "  </metadata>",
    indentXml(waypoints, 2),
    "</gpx>"
  ].join("\n");
}

function escapeCsv(value) {
  if (value === null || value === undefined) {
    return "";
  }

  const stringValue = String(value);
  if (stringValue.includes(",") || stringValue.includes("\"") || stringValue.includes("\n")) {
    return `"${stringValue.replaceAll("\"", "\"\"")}"`;
  }
  return stringValue;
}

function escapeXml(value) {
  if (value === null || value === undefined) {
    return "";
  }

  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function indentXml(xml, spaces) {
  const prefix = " ".repeat(spaces);
  return xml
    .split("\n")
    .map((line) => (line ? `${prefix}${line}` : line))
    .join("\n");
}
